name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
 
    - name: g++ test
      run: |
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
        g++ --version
        sudo update-alternatives --auto g++ 
        g++ --version
        
    - name: check
      run: |
        sudo ll /usr/local/include
      
