name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
#     runs-on: ubuntu-latest
    container: cdecl/gcc-boost
    steps:
    - uses: actions/checkout@v2
    - name: check
      run: |
        cat /etc/*-release
      
