name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test1
      run: |
        ls -l
    - name: test2
      run: |
        cat /etc/*-release
        docker --version
        g++-9 --version
        alias g++=g++-9
        
    - name: check
      run: |
        g++ --version
      
