name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test1
      run: |
        ls -l
    - name: test2
      run: |
        cat /etc/*-release
        docker --version
        g++-9 --version
    - name: g++ teste
      run: |
        sudo update-alternatives --install /usr/bin/g++   g++  /usr/bin/g++-9 
        g++ --version
        sudo update-alternatives --auto g++ 
        g++ --version
        
    - name: check
      run: |
        g++ --version
      
